function(assemble_rule target)
    set(inputVar "${MP_CC};-c;${MP_EXTRA_AS_PRE};-mcpu=18F47Q84;-mdfp=C:/Users/ethan/.mchp_packs/Microchip/PIC18F-Q_DFP/1.24.430/xc8;-fno-short-double;-fno-short-float;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=0;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-download;-mno-default-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(assemblePreprocess_rule target)
    set(inputVar "-c;${MP_EXTRA_AS_PRE};-mcpu=18F47Q84;-mdfp=C:/Users/ethan/.mchp_packs/Microchip/PIC18F-Q_DFP/1.24.430/xc8;-fno-short-double;-fno-short-float;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=0;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-download;-mno-default-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(compile_rule target)
    set(inputVar "${MP_CC};${MP_EXTRA_CC_PRE};-mcpu=18F47Q84;-c;-mdfp=C:/Users/ethan/.mchp_packs/Microchip/PIC18F-Q_DFP/1.24.430/xc8;-fno-short-double;-fno-short-float;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=0;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-download;-mno-default-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-mcpu=18F47Q84;-Wl,-Map=mem.map;-DXPRJ_default=default;-Wl,--defsym=__MPLAB_BUILD=1;-mdfp=C:/Users/ethan/.mchp_packs/Microchip/PIC18F-Q_DFP/1.24.430/xc8;-fno-short-double;-fno-short-float;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=0;-Wa,-a;-msummary=-psect,-class,+mem,-hex,-file;-ginhx32;-Wl,--data-init;-mno-keep-startup;-mno-download;-mno-default-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-Wl,--memorysummary,memoryfile.xml,")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
